languageCode = "en-us"
footnotereturnlinkcontents = "↩"
builddrafts = false
title = "STARDOG★WEBLOG"
baseurl = "/"
canonifyurls = true
copyright = "https://creativecommons.org/licenses/by-sa/3.0/"

[permalinks]
  posts = "/:title/"

[params]
  description = ""
  author = "Stardog Union"
  sidebarrecentlimit = 3
  
